#!/usr/bin/env python3
"""Generate a packed Unifont glyph subset header for the ThinkNode M1 native UI.

Reads GNU Unifont .hex files (BMP + upper/SMP planes) and emits a C header with a
sorted codepoint index (binary-searchable) and a 1-bit glyph blob. Each glyph is 16
rows tall; width is 8 (16 bytes) or 16 (32 bytes), taken straight from the .hex.

Usage:
  python3 tools/gen_unifont.py unifont.hex unifont_upper.hex \
      examples/companion_radio/ui-elements/unifont_glyphs.h
"""
import sys

# Codepoint ranges to include (inclusive). Latin + punctuation + symbols + arrows.
RANGES = [
    (0x0020, 0x007E),  # ASCII
    (0x00A0, 0x00FF),  # Latin-1 Supplement (accents, °, £, ©, ±, …)
    (0x0100, 0x017F),  # Latin Extended-A
    (0x2010, 0x2027),  # General Punctuation (dashes, smart quotes, bullet, ellipsis)
    (0x2030, 0x205E),  # more punctuation (‰, ‹›, ※, etc.)
    (0x20A0, 0x20BF),  # Currency symbols (€, ₿, etc.)
    (0x2100, 0x214F),  # Letterlike Symbols (™, ℃, ℉, №, ℗, Ω, …)
    (0x2190, 0x21FF),  # Arrows
    (0x2300, 0x23FF),  # Misc Technical (⌚, ⌛, ⏰, ⏻, …)
    (0x2460, 0x24FF),  # Enclosed Alphanumerics (①..⑳, ⓐ..ⓩ)
    (0x2500, 0x257F),  # Box Drawing (─│┌┐└┘├┼, borders/ASCII art)
    (0x2580, 0x25FF),  # Block Elements (▁..█ battery gauge) + Geometric Shapes (▲▶▼◀●)
    (0x2600, 0x26FF),  # Misc Symbols (☀, ☎, ★, ⚡, ♠♥♦♣, ♚, ⚀..⚅ dice, ♩♪♫, …)
    (0x2700, 0x27BF),  # Dingbats (✓, ✔, ✗, ➤, ✉, …)
    (0x2800, 0x28FF),  # Braille Patterns (⠀..⣿, fine art / spinners)
    (0x2B00, 0x2BFF),  # Misc Symbols & Arrows (⭐, ⬆⬇, ⬛⬜, …)
    # --- Plane 1 (monochrome 16x16 in Unifont) ---
    (0x1F000, 0x1F02F),  # Mahjong Tiles (🀄, …)
    (0x1F030, 0x1F09F),  # Domino Tiles
    (0x1F0A0, 0x1F0FF),  # Playing Cards (🃏 joker + full deck)
    (0x1F300, 0x1F5FF),  # Misc Symbols & Pictographs (weather 🌤🌧🌨, nature, objects, food, …)
    (0x1F600, 0x1F64F),  # Emoticons (😀 … 🙏)
    (0x1F680, 0x1F6FF),  # Transport & Map (🚀🚗🛰, ⚠ signs, …)
    (0x1F900, 0x1F9FF),  # Supplemental Symbols & Pictographs (🧭🧰🧪, more objects)
]

# Curated individual Plane-1 codepoints (UI symbols + a few common emoji).
EXTRA = [
    0x1F4F1,  # 📱 mobile phone (app connected)
    0x1F4CD,  # 📍 round pushpin (GPS)
    0x1F507,  # 🔇 muted speaker
    0x1F508, 0x1F509, 0x1F50A,  # speaker low/med/high
    0x1F50B,  # 🔋 battery
    0x1F4F6,  # 📶 signal bars
    0x1F4E1,  # 📡 satellite antenna
    0x1F44D, 0x1F44E,  # 👍 👎
    0x1F389,  # 🎉 party popper
    0x1F4AC,  # 💬 speech balloon
]


def load_hex(path):
    glyphs = {}
    with open(path, "r") as f:
        for line in f:
            line = line.strip()
            if not line or ":" not in line:
                continue
            cp_s, bits = line.split(":", 1)
            glyphs[int(cp_s, 16)] = bits.strip()
    return glyphs


def wanted():
    cps = set()
    for lo, hi in RANGES:
        cps.update(range(lo, hi + 1))
    cps.update(EXTRA)
    return cps


def main():
    if len(sys.argv) != 4:
        sys.exit(__doc__)
    bmp_path, upper_path, out_path = sys.argv[1:4]
    glyphs = load_hex(bmp_path)
    glyphs.update(load_hex(upper_path))  # upper planes (emoji) override/extend

    want = wanted()
    selected = sorted(cp for cp in want if cp in glyphs)

    blob = bytearray()
    index = []  # (cp, offset, width)
    for cp in selected:
        hexs = glyphs[cp]
        nbytes = len(hexs) // 2
        width = 8 if nbytes == 16 else 16  # 16 rows; 16B->8w, 32B->16w
        index.append((cp, len(blob), width))
        blob += bytes.fromhex(hexs)

    with open(out_path, "w") as o:
        o.write("// Generated by tools/gen_unifont.py from GNU Unifont -- do not edit.\n")
        o.write("// 1-bit glyphs, 16 rows tall; width 8 (16B) or 16 (32B), MSB-first.\n")
        o.write("#pragma once\n#include <stdint.h>\n\n")
        o.write(f"#define UNIFONT_GLYPH_COUNT {len(index)}\n")
        o.write("#define UNIFONT_ROWS 16\n\n")

        o.write("const uint32_t unifont_cp[UNIFONT_GLYPH_COUNT] = {\n")
        for i in range(0, len(index), 12):
            o.write("  " + ",".join("0x%X" % c for c, _, _ in index[i:i+12]) + ",\n")
        o.write("};\n\n")

        o.write("const uint32_t unifont_off[UNIFONT_GLYPH_COUNT] = {\n")
        for i in range(0, len(index), 12):
            o.write("  " + ",".join(str(off) for _, off, _ in index[i:i+12]) + ",\n")
        o.write("};\n\n")

        o.write("const uint8_t unifont_w[UNIFONT_GLYPH_COUNT] = {\n")
        for i in range(0, len(index), 24):
            o.write("  " + ",".join(str(w) for _, _, w in index[i:i+24]) + ",\n")
        o.write("};\n\n")

        o.write(f"const uint8_t unifont_bits[{len(blob)}] = {{\n")
        for i in range(0, len(blob), 20):
            o.write("  " + ",".join("0x%02X" % b for b in blob[i:i+20]) + ",\n")
        o.write("};\n")

    idx_bytes = len(index) * (4 + 4 + 1)
    print(f"glyphs: {len(index)}")
    print(f"bitmap blob: {len(blob)} bytes")
    print(f"index: ~{idx_bytes} bytes")
    print(f"total flash: ~{(len(blob)+idx_bytes)//1024} KB -> {out_path}")


if __name__ == "__main__":
    main()
